name:                superrocks
version:             0.1.0.0
github:              "agrafix/superrocks"
license:             BSD3
author:              "Alexander Thiemann"
maintainer:          "mail@athiemann.net"
copyright:           "2018 Alexander Thiemann <mail@athiemann.net>"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis:            A high level interface to RocksDB
category:            Data
description:         Various high level interfaces for reading and writing data to RocksDB.

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.5
  - time >= 1.8
  - rocksdb-haskell >= 1.0.1

library:
  source-dirs: src
  dependencies:
    - text >= 1.2
    - cborg >= 0.2
    - cborg-json >= 0.2
    - serialise >= 0.2
    - batch >= 0.1
    - timespan >= 0.3
    - bytestring >= 0.10
    - aeson >= 1.2
    - mtl >= 2.2
    - resourcet >= 1.1

tests:
  superrocks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - superrocks
      - hspec
      - temporary
      - QuickCheck
