name:                superrocks
version:             0.1.0.0
github:              "agrafix/superrocks"
license:             BSD3
author:              "Alexander Thiemann"
maintainer:          "mail@athiemann.net"
copyright:           "2018 Alexander Thiemann <mail@athiemann.net>"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis:            A high level interface to RocksDB
category:            Data
description:         Various high level interfaces for reading and writing data to RocksDB.

dependencies:
  - base >= 4.7 && < 5
  - containers
  - time
  - rocksdb-haskell

library:
  source-dirs: src
  dependencies:
    - text
    - cborg
    - cborg-json
    - serialise
    - batch
    - timespan
    - bytestring
    - aeson
    - mtl
    - resourcet

tests:
  superrocks-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - superrocks
      - hspec
      - temporary
      - QuickCheck
